### ISSUE TITLE
Remove calls to `size/1` and use instead `tuple_size/1` or `byte_size/1`

### ISSUE THREAD

**Issue by kikofernandez** [erlang/otp#6672]
**Describe the bug**
The BIF `size/1` works on tuples and binaries. 
To get the JIT to optimise code, OTP code should call in its stead `tuple_size/1` or `byte_size/1`.
Affected modules:
- [x] lib/sasl/src/systools_rc.erl (#6699 )
- [x] lib/eunit/src/eunit_data.erl (#6671 )
- [x] lib/mnesia/test/mnesia_consistency_test.erl (#6695 )
- [x] lib/kernel/test/gen_udp_SUITE.erl (#6700 )
- [x] lib/kernel/src/erts_debug.erl
- [x] lib/kernel/doc/src/socket.xml
- [x] lib/inets/test/httpd_time_test.erl (#6670 )
- [x] lib/inets/test/httpd_poll.erl (#6670 )
- [x] lib/snmp/test/snmp_test_lib.erl (#6694 )
- [x] lib/snmp/test/snmp_agent_SUITE.erl (#6694 )
- [x] lib/snmp/test/snmp_test_mgr_misc.erl (#6694 )
- [x] lib/snmp/test/snmp_test_mgr.erl (#6694 )
- [x] lib/snmp/src/agent/snmpa_net_if.erl (#6694 )
- [x] lib/public_key/src/public_key.erl (#6673 )
- [x] lib/stdlib/test/erl_eval_SUITE.erl (these seem to test `size/1`, so I let them be)
- [x] lib/stdlib/test/erl_lint_SUITE.erl..(same as above)
- [x] lib/stdlib/test/shell_SUITE.erl ....(same as above)
- [x] lib/stdlib/test/qlc_SUITE.erl .......(same as above)
- [x] lib/stdlib/src/gb_sets.erl
- [x] lib/stdlib/src/gb_trees.erl
- [x] lib/ssh/test/ssh_basic_SUITE.erl (#6696 )
- [x] lib/ssh/src/ssh_dbg.erl (#6696 )
- [x] lib/ssh/src/ssh_options.erl (#6696 )
- [x] lib/ssh/src/ssh.erl (#6696 )
- [x] lib/eldap/ebin/ELDAPv3.erl
- [x] lib/diameter/test/diameter_gen_tcp_SUITE.erl (#6702 )
- [x] lib/diameter/test/diameter_codec_test.erl (#6702 )
- [x] lib/diameter/src/base/diameter_lib.erl (#6702 )
- [x] lib/diameter/src/base/diameter_codec.erl (#6702 )
- [x] lib/diameter/src/base/diameter_types.erl (#6702 )
- [x] lib/diameter/src/info/diameter_info.erl (#6702 )
- [x] lib/debugger/test/erl_eval_SUITE.erl (#6703 )
- [x] lib/debugger/test/overridden_bif_SUITE.erl (#6703 )
- [x] lib/debugger/test/guard_SUITE.erl (#6703 )
- [x] lib/debugger/test/bs_match_bin_SUITE.erl (#6703 )
- [x] lib/dialyzer/test/options1_SUITE_data/src/compiler/cerl_inline.erl (#6684 )
- [x] lib/dialyzer/test/options1_SUITE_data/src/compiler/cerl.erl (#6684 )
- [x] lib/dialyzer/test/user_SUITE_data/src/wsp_pdu.erl (#6684 )
- [x] lib/dialyzer/test/r9c_SUITE_data/src/mnesia/mnesia.erl
- [x] lib/dialyzer/test/r9c_SUITE_data/src/inets/http_lib.erl
- [x] lib/dialyzer/test/r9c_SUITE_data/src/inets/httpd_request_handler.erl
- [x] lib/dialyzer/test/r9c_SUITE_data/src/inets/httpd_socket.erl
- [x] lib/dialyzer/test/r9c_SUITE_data/src/asn1/asn1rt_ber_bin_v2.erl
- [x] lib/asn1/test/asn1_SUITE_data/RANAP.asn1
- [x] lib/common_test/test/test_server_SUITE.erl
- [x] lib/common_test/src/ct_framework.erl
- [x] lib/compiler/test/overridden_bif_SUITE.erl
- [x] lib/compiler/test/guard_SUITE.erl (#6704 )
- [x] lib/xmerl/doc/examples/test_html.erl (#6674 )

**Affected versions**
OTP-24+

**Additional context**
This issue comes from #6669 . This will be a joint effort, so please update and mark as solved the PRs that fix one of the modules

**Comment by kikofernandez** [comment]
These PRs will fix some of these issues: #6669 #6670 #6671 
I will update the checkmark when merged

**Comment by bjorng** [comment]
`lib/asn1/test/asn1_SUITE_data/RANAP.asn1` is an ASN.1 spec and it does not call `size/1`. (It contains a comment with the text "size(s)".)

**Comment by bjorng** [comment]
The `erts_debug` module does not call the guard BIF `size/1`; it defines its own `size/1` function and calls that.

**Comment by bjorng** [comment]
The list of calls to `size/1` above does not seem to be complete. The test case `otp_SUITE:calls_to_size_1/1` that runs `xref` found the following calls to `size/1`:

```
crypto:block_encrypt/2 calls non-recommended erlang:size/1
crypto:srp_pad_to/2 calls non-recommended erlang:size/1
diameter_dbg:data/3 calls non-recommended erlang:size/1
diameter_dbg:pp/1 calls non-recommended erlang:size/1
diameter_dbg:un/3 calls non-recommended erlang:size/1
diameter_peer_fsm:recv/4 calls non-recommended erlang:size/1
ftp:file_read/1 calls non-recommended erlang:size/1
ftp:open_options/1 calls non-recommended erlang:size/1
ftp:progress_report/2 calls non-recommended erlang:size/1
ftp_response:parse_lines/3 calls non-recommended erlang:size/1
httpd_request_handler:handle_msg/2 calls non-recommended erlang:size/1
httpd_util:flatlength/2 calls non-recommended erlang:size/1
megaco_filter:do_filter_contents/4 calls non-recommended erlang:size/1
megaco_flex_scanner:is_own_port/2 calls non-recommended erlang:size/1
megaco_messenger_misc:encode_action_replies/4 calls non-recommended erlang:size/1
megaco_tcp:add_tpkt_header/1 calls non-recommended erlang:size/1
megaco_tcp_connection:handle_info/2 calls non-recommended erlang:size/1
megaco_trans_sender:handle_send_req/3 calls non-recommended erlang:size/1
megaco_trans_sender:loop/2 calls non-recommended erlang:size/1
megaco_trans_sender:maybe_send_reqs/7 calls non-recommended erlang:size/1
megaco_trans_sender:send_reply/6 calls non-recommended erlang:size/1
megaco_udp:send_message/2 calls non-recommended erlang:size/1
megaco_udp_server:handle_info/2 calls non-recommended erlang:size/1
mnesia_index:init_disc_index/3 calls non-recommended erlang:size/1
mnesia_lib:error_desc/1 calls non-recommended erlang:size/1
mnesia_loader:calc_nokeys/2 calls non-recommended erlang:size/1
mnesia_schema:assert_correct_cstruct/1 calls non-recommended erlang:size/1
mnesia_schema:transform_obj/9 calls non-recommended erlang:size/1
mnesia_schema:write_table_property/2 calls non-recommended erlang:size/1
mnesia_snmp_hook:key_to_oid_i/2 calls non-recommended erlang:size/1
mnesia_snmp_hook:oid_to_key_1/2 calls non-recommended erlang:size/1
snmp_generic_mnesia:make_row_list/1 calls non-recommended erlang:size/1
snmp_index:key_to_oid_i/2 calls non-recommended erlang:size/1
snmp_pdus:enc_oct_str_tag/1 calls non-recommended erlang:size/1
snmpa_local_db:get_elements/2 calls non-recommended erlang:size/1
snmpa_mib_data_tttn:find_next/5 calls non-recommended erlang:size/1
snmpa_mib_data_tttn:next_node/5 calls non-recommended erlang:size/1
snmpa_mpd:generate_msg/6 calls non-recommended erlang:size/1
snmpa_mpd:generate_response_msg/7 calls non-recommended erlang:size/1
snmpa_mpd:mk_v3_packet_entry/9 calls non-recommended erlang:size/1
snmpm_mpd:generate_v1_v2c_msg/4 calls non-recommended erlang:size/1
snmpm_mpd:generate_v1_v2c_response_msg/4 calls non-recommended erlang:size/1
snmpm_mpd:generate_v3_response_msg/9 calls non-recommended erlang:size/1
snmpm_mpd:process_v3_msg/6 calls non-recommended erlang:size/1
snmpm_mpd:sec_error/2 calls non-recommended erlang:size/1
snmpm_net_if:handle_recv_msg/4 calls non-recommended erlang:size/1
snmpm_net_if_mt:handle_recv_msg/4 calls non-recommended erlang:size/1
ssh_agent:encode/1 calls non-recommended erlang:size/1
ssh_agent:pack/1 calls non-recommended erlang:size/1
ssh_auth:build_sig_data/5 calls non-recommended erlang:size/1
ssh_auth:handle_userauth_request/3 calls non-recommended erlang:size/1
ssh_auth:keyboard_interactive_msg/1 calls non-recommended erlang:size/1
ssh_auth:password_msg/1 calls non-recommended erlang:size/1
ssh_auth:publickey_msg/1 calls non-recommended erlang:size/1
ssh_bits:mpint/1 calls non-recommended erlang:size/1
ssh_client_channel:adjust_window/1 calls non-recommended erlang:size/1
ssh_client_channel:handle_info/2 calls non-recommended erlang:size/1
ssh_connection:channel_data_reply_msg/4 calls non-recommended erlang:size/1
ssh_connection:encode_pty_opts/1 calls non-recommended erlang:size/1
ssh_connection:exec/4 calls non-recommended erlang:size/1
ssh_connection:get_window/2 calls non-recommended erlang:size/1
ssh_connection:pty_req/9 calls non-recommended erlang:size/1
ssh_connection:setenv/6 calls non-recommended erlang:size/1
ssh_connection:signal/3 calls non-recommended erlang:size/1
ssh_connection:subsystem/4 calls non-recommended erlang:size/1
ssh_connection_handler:handle_event/4 calls non-recommended erlang:size/1
ssh_file:decode/2 calls non-recommended erlang:size/1
ssh_file:openssh_key_v1_encode/1 calls non-recommended erlang:size/1
ssh_file:openssh_key_v1_encode_priv_keys_cmnts/2 calls non-recommended erlang:size/1
ssh_file:openssh_key_v1_encode_pub_keys/2 calls non-recommended erlang:size/1
ssh_file:pos_match/2 calls non-recommended erlang:size/1
ssh_message:encode/1 calls non-recommended erlang:size/1
ssh_message:encode_signature/3 calls non-recommended erlang:size/1
ssh_message:ssh2_privkey_encode/1 calls non-recommended erlang:size/1
ssh_message:ssh2_pubkey_encode/1 calls non-recommended erlang:size/1
ssh_sftp:do_handle_call/3 calls non-recommended erlang:size/1
ssh_sftp:do_the_read_buf/6 calls non-recommended erlang:size/1
ssh_sftp:do_the_write_buf/5 calls non-recommended erlang:size/1
ssh_sftp:position_buf/5 calls non-recommended erlang:size/1
ssh_sftp:read_rpt/6 calls non-recommended erlang:size/1
ssh_sftp:write_file/4 calls non-recommended erlang:size/1
ssh_sftp:write_to_remote_tar/4 calls non-recommended erlang:size/1
ssh_tcpip_forward_acceptor:acceptor_loop/7 calls non-recommended erlang:size/1
ssh_transport:get_length/4 calls non-recommended erlang:size/1
ssh_transport:handle_packet_part/5 calls non-recommended erlang:size/1
ssh_transport:kex_alg_dependent/1 calls non-recommended erlang:size/1
ssh_transport:kex_plaintext/3 calls non-recommended erlang:size/1
ssh_transport:pack/5 calls non-recommended erlang:size/1
ssh_transport:unpack/7 calls non-recommended erlang:size/1
ssh_xfer:close/3 calls non-recommended erlang:size/1
ssh_xfer:encode_As/4 calls non-recommended erlang:size/1
ssh_xfer:encode_acl_items/1 calls non-recommended erlang:size/1
ssh_xfer:encode_ext/1 calls non-recommended erlang:size/1
ssh_xfer:encode_name/3 calls non-recommended erlang:size/1
ssh_xfer:extended/4 calls non-recommended erlang:size/1
ssh_xfer:fsetstat/4 calls non-recommended erlang:size/1
ssh_xfer:fstat/4 calls non-recommended erlang:size/1
ssh_xfer:lstat/4 calls non-recommended erlang:size/1
ssh_xfer:mkdir/4 calls non-recommended erlang:size/1
ssh_xfer:open/6 calls non-recommended erlang:size/1
ssh_xfer:opendir/3 calls non-recommended erlang:size/1
ssh_xfer:read/5 calls non-recommended erlang:size/1
ssh_xfer:readdir/3 calls non-recommended erlang:size/1
ssh_xfer:readlink/3 calls non-recommended erlang:size/1
ssh_xfer:realpath/3 calls non-recommended erlang:size/1
ssh_xfer:remove/3 calls non-recommended erlang:size/1
ssh_xfer:rename/5 calls non-recommended erlang:size/1
ssh_xfer:rmdir/3 calls non-recommended erlang:size/1
ssh_xfer:setstat/4 calls non-recommended erlang:size/1
ssh_xfer:stat/4 calls non-recommended erlang:size/1
ssh_xfer:symlink/4 calls non-recommended erlang:size/1
ssh_xfer:write/5 calls non-recommended erlang:size/1
ssh_xfer:xf_request/3 calls non-recommended erlang:size/1
ssh_xfer:xf_send_attr/3 calls non-recommended erlang:size/1
ssh_xfer:xf_send_data/3 calls non-recommended erlang:size/1
ssh_xfer:xf_send_reply/3 calls non-recommended erlang:size/1
ssh_xfer:xf_send_status/5 calls non-recommended erlang:size/1
ssl_cipher:aead_decrypt/6 calls non-recommended erlang:size/1
ssl_cipher:aead_encrypt/6 calls non-recommended erlang:size/1
ssl_trace:trace_ts/1 calls non-recommended erlang:size/1
tftp_binary:do_handle_options/3 calls non-recommended erlang:size/1
tftp_binary:prepare/6 calls non-recommended erlang:size/1
tftp_binary:read/1 calls non-recommended erlang:size/1
tftp_binary:write/2 calls non-recommended erlang:size/1
tftp_engine:do_callback/4 calls non-recommended erlang:size/1
tftp_engine:do_print_debug_info/4 calls non-recommended erlang:size/1
tftp_engine:peer_info/1 calls non-recommended erlang:size/1
tftp_file:read/1 calls non-recommended erlang:size/1
tftp_file:write/2 calls non-recommended erlang:size/1
tftp_lib:do_parse_config/2 calls non-recommended erlang:size/1
tls_gen_connection:handle_info/3 calls non-recommended erlang:size/1
xmerl_eventp:find_good_split/7 calls non-recommended erlang:size/1
```

**Comment by kikofernandez** [comment]
Thanks! I will look into those as well :)
